# July 2022

## Week of 2022-07-03

- [Setup Cypress & Applitools with GitHub Actions: a comparison of Applitools vs Percy in a mid size app](https://dev.to/muratkeremozcan/setup-cypress-applitools-with-github-actions-a-comparison-of-applitools-vs-percy-in-a-mid-size-app-43ij) @blog

## Week of 2022-07-10

- Cypress 10 migration (monorepos, test plugins, onboarding) @testing
- [Triple combined code coverage for React Apps with Jest, Cypress component and e2e tests, using Github Actions](https://dev.to/muratkeremozcan/triple-combined-code-coverage-for-react-apps-with-jest-cypress-component-and-e2e-tests-using-github-actions-1icc) @blog

## Week of 2022-07-17

- [Cypress component test setup, and a sample test for Zen](https://github.com/helloextend/client/pull/4463) @testing
- [Component test setup for Instore](https://github.com/helloextend/client/pull/4490) @testing
- [Component test setup for Merchants](https://github.com/helloextend/client/pull/4493) @testing

## Week of 2022-07-24

- [Component test setup for Portal](https://github.com/helloextend/client/pull/4507) @testing
- [Component test setup for Customers](https://github.com/helloextend/client/pull/4520) @testing
